name: root
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - c-ares=1.16.1=h516909a_3
  - ca-certificates=2020.6.20=hecda079_0
  - certifi=2020.6.20=py36h9880bd3_2
  - cffi=1.14.3=py36h829019c_1
  - chardet=3.0.4=py36_2
  - cryptography=3.1.1=py36h45558ae_0
  - conda=4.3.21=py36_0
  - conda-env=2.6.0=0
  - cytoolz=0.8.2=py36_0
  - gperftools=2.7=h767d802_2
  - h5py=2.10.0=nompi_py36ha233d17_105
  - hdf5=1.10.6=nompi_h54c07f9_1110
  - jpeg=9d=h516909a_0
  - krb5=1.17.1=hfafb76e_3
  - ld_impl_linux-64=2.35=h769bd43_9
  - libblas=3.9.0=2_openblas
  - libcblas=3.9.0=2_openblas
  - libcurl=7.71.1=hcdd3856_8
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=9.3.0=h5dbcf3e_17
  - libgfortran-ng=9.3.0=he4bcb1c_17
  - libgfortran4=7.5.0=hae1eefd_17
  - libgfortran5=9.3.0=he4bcb1c_17
  - libgomp=9.3.0=h5dbcf3e_17
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=2_openblas
  - libnghttp2=1.41.0=h8cfc5f6_2
  - libopenblas=0.3.12=pthreads_hb3c22a3_1
  - libssh2=1.9.0=hab1572f_5
  - libstdcxx-ng=9.3.0=h2ae2ef3_17
  - numpy=1.18.5=py36h7314795_0
  - ncurses=6.2=h58526e2_3
  - openssl=1.1.1h=h516909a_0
  - perl=5.32.0=h36c2ea0_0
  - pip=20.2.4=py_0
  - pygments=2.7.3
  - pyopenssl=19.1.0=py36_0
  - python=3.6.11=h6f2ec95_2_cpython
  - python_abi=3.6=1_cp36m
  - readline=8.0=he28a2e2_2
  - requests=2.24.0
  - sentencepiece=0.1.92=py36hdb11119_0
  - setuptools=41.4.0=py36_0
  - six=1.15.0=pyh9f0ad1d_0
  - sqlite=3.33.0=h4cf870e_1
  - tk=8.6.10=hed695b0_1
  - toolz=0.11.1=py_0
  - urllib3=1.25.10
  - unixodbc=2.3.9=h0e019cf_0
  - xz=5.2.5=h516909a_1
  - wheel=0.30.0=py36_2
  - yaml=0.2.5=h516909a_0
  - zlib=1.2.11=h516909a_1010
  - pip:
    - absl-py==0.11.0
    - adal==1.2.4
    - adlfs==0.5.5
    - aiohttp==3.7.2
    - alembic==1.4.1
    - altair==4.1.0
    - appdirs==1.4.4
    - applicationinsights==0.11.9
    - asn1crypto==1.4.0
    - astor==0.8.1
    - astroid==2.4.2
    - astunparse==1.6.3
    - async-timeout==3.0.1
    - attrs==20.3.0
    - azure-common==1.1.25
    - azure-core==1.8.2
    - azure-datalake-store==0.0.51
    - azure-graphrbac==0.61.1
    - azure-identity==1.4.1
    - azure-mgmt-authorization==0.61.0
    - azure-mgmt-containerregistry==2.8.0
    - azure-mgmt-keyvault==2.2.0
    - azure-mgmt-resource==10.2.0
    - azure-mgmt-storage==11.2.0
    - azure-storage-blob==12.5.0
    - azure-storage-common==2.1.0
    - azureml-automl-core==1.16.0
    - azureml-automl-runtime==1.16.0
    - azureml-core==1.16.0
    - azureml-dataprep==2.3.1
    - azureml-dataprep-native==23.0.0
    - azureml-dataprep-rslex==1.1.1
    - azureml-dataset-runtime==1.16.0
    - azureml-defaults==1.16.0
    - azureml-interpret==1.16.0
    - azureml-mlflow==1.16.0
    - azureml-model-management-sdk==1.0.1b6.post1
    - azureml-opendatasets==1.18.0
    - azureml-pipeline==1.16.0
    - azureml-pipeline-core==1.16.0
    - azureml-pipeline-steps==1.16.0
    - azureml-sdk==1.16.0
    - azure-storage-blob==12.5.0
    - azureml-telemetry==1.16.0
    - azureml-train==1.16.0
    - azureml-train-automl==1.16.0
    - azureml-train-automl-client==1.16.0
    - azureml-train-automl-runtime==1.16.0
    - azureml-train-core==1.16.0
    - azureml-train-restclients-hyperdrive==1.16.0
    - backports.tempfile==1.0
    - backports.weakref==1.0.post1
    - beautifulsoup4==4.9.3
    - bitarray==1.6.1
    - bokeh==2.2.3
    - boto==2.49.0
    - boto3==1.15.14
    - botocore==1.18.14
    - Bottleneck==1.3.2
    - bpemb==0.3.2
    - cachetools==4.1.1
    - certifi==2020.6.20
    - click==7.1.2
    - cloudpickle==1.6.0
    - configparser==3.7.4
    - contextlib2==0.6.0.post1
    - cycler==0.10.0
    - cython==0.29.21
    - cytoolz==0.8.2
    - databricks-cli==0.14.0
    - dataclasses==0.8
    - datashape==0.5.2
    - decorator==4.4.2
    - Deprecated==1.2.10
    - dill==0.3.2
    - distro==1.5.0
    - docker==4.3.1
    - docutils==0.16
    - dotnetcore2==2.1.17
    - entrypoints==0.3
    - et-xmlfile==1.0.1
    - filelock==3.0.12
    - fire==0.3.1
    - flair==0.5
    - Flask==1.0.3
    - fsspec==0.8.4
    - fusepy==3.0.1
    - future==0.18.2
    - gast==0.3.3
    - gensim==3.8.3
    - geographiclib==1.50
    - geopy==2.0.0
    - gitdb==4.0.5
    - GitPython==3.1.11
    - google-auth==1.23.0
    - google-auth-oauthlib==0.4.2
    - google-pasta==0.2.0
    - gorilla==0.3.0
    - grpcio==1.33.2
    - gunicorn==19.9.0
    - html5lib==1.1
    - hummingbird-ml==0.0.6
    - hyperopt==0.2.5
    - idna==2.10
    - idna-ssl==1.1.0
    - imageio==2.9.0
    - importlib-metadata==1.7.0
    - interpret-community==0.15.1
    - interpret-core==0.2.1
    - ipython==7.8.0
    - ipython-genutils==0.2.0
    - isodate==0.6.0
    - isort==5.6.4
    - itsdangerous==1.1.0
    - jdcal==1.4.1
    - jeepney==0.4.3
    - Jinja2==2.11.2
    - jmespath==0.10.0
    - joblib==0.14.1
    - json-logging-py==0.2
    - jsonpickle==1.4.1
    - jsonschema==3.2.0
    - Keras-Applications==1.0.8
    - Keras-Preprocessing==1.1.2
    - keras2onnx==1.6.0
    - kiwisolver==1.3.1
    - koalas==1.2.0
    - langdetect==1.0.8
    - lazy-object-proxy==1.4.3
    - liac-arff==2.5.0
    - lightgbm==2.3.0
    - Mako==1.1.3
    - Markdown==3.3.3
    - MarkupSafe==1.1.1
    - matplotlib==3.2.2
    - mccabe==0.6.1
    - mistune==0.8.4
    - mleap==0.16.1
    - mlflow==1.11.0
    - more-itertools==8.6.0
    - mpld3==0.3
    - mpmath==1.1.0
    - msal==1.5.0
    - msal-extensions==0.2.2
    - msrest==0.6.19
    - msrestazure==0.6.4
    - multidict==5.0.0
    - multipledispatch==0.6.0
    - mypy==0.780
    - mypy-extensions==0.4.3
    - ndg-httpsclient==0.5.1
    - networkx==2.5
    - nimbusml==1.7.1
    - nltk==3.5
    - nose==1.3.7
    - oauthlib==3.1.0
    - odo==0.5.0
    - olefile==0.46
    - onnx==1.6.0
    - onnxconverter-common==1.6.0
    - onnxmltools==1.4.1
    - onnxruntime==1.3.0
    - openpyxl==3.0.5
    - opt-einsum==3.3.0
    - packaging==20.4
    - pandas==0.25.3
    - pandasql==0.7.3
    - pathspec==0.8.0
    - patsy==0.5.1
    - pickleshare==0.7.5
    - Pillow==8.0.1
    - plotly==4.12.0
    - pluggy==0.13.1
    - pmdarima==1.1.1
    - portalocker==1.7.1
    - prometheus-client==0.8.0
    - prometheus-flask-exporter==0.18.1
    - protobuf==3.13.0
    - psutil==5.7.2
    - py==1.9.0
    - py-cpuinfo==5.0.0
    - py4j==0.10.7
    - pyarrow==1.0.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycrypto==2.6.1
    - PyJWT==1.7.1
    - pylint==2.6.0
    - pymssql==2.1.5
    - pyodbc==4.0.30
    - pyopencl==2020.1
    - pyparsing==2.4.7
    - pyrsistent==0.17.3
    - pyspark==2.4.5
    - pytest==5.3.2
    - python-dateutil==2.8.1
    - python-editor==1.0.4
    - pytools==2021.1
    - pytz==2020.1
    - PyWavelets==1.1.1
    - PyYAML==5.3.1
    - querystring-parser==1.2.4
    - regex==2020.10.28
    - requests-oauthlib==1.3.0
    - retrying==1.3.3
    - rsa==4.6
    - ruamel.yaml==0.16.12
    - ruamel.yaml.clib==0.2.2
    - s3transfer==0.3.3
    - sacremoses==0.0.43
    - scikit-image==0.17.2
    - scikit-learn==0.22.2.post1
    - scipy==1.4.1
    - seaborn==0.11.0
    - SecretStorage==3.1.2
    - segtok==1.5.10
    - shap==0.34.0
    - skl2onnx==1.4.9
    - sklearn-pandas==1.7.0
    - smart-open==1.9.0
    - smmap==3.0.4
    - soupsieve==2.0.1
    - SQLAlchemy==1.3.13
    - sqlitedict==1.7.0
    - sqlparse==0.4.1
    - statsmodels==0.10.2
    - tabulate==0.8.7
    - tb-nightly==1.14.0a20190603
    - tensorboard==2.3.0
    - tensorboard-plugin-wit==1.7.0
    - tensorflow==2.0.0b1
    - tensorflow-estimator==2.3.0
    - termcolor==1.1.0
    - textblob==0.15.3
    - tf-estimator-nightly==1.14.0.dev2019060501
    - tf2onnx==1.7.2
    - tifffile==2020.9.3
    - tokenizers==0.9.2
    - toml==0.10.2
    - torch==1.7.0
    - tornado==6.1
    - tqdm==4.48.2
    - transformers==3.4.0
    - typed-ast==1.4.1
    - typing-extensions==3.7.4.3
    - urllib3==1.25.10
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==0.57.0
    - Werkzeug==0.16.1
    - wheel==0.30.0
    - wrapt==1.11.2
    - xgboost==0.90 
    - zict==1.0.0
    - zipp==0.6.0
prefix: /usr/lib/anaconda3